EXTRA_DIST += \
 tests/concurrent-write-bench.sh\
 tests/abt-io-benchmark.sh\
 tests/basic-uring.sh\
 tests/abt-io-uring-cfg-example.json\
 tests/abt-io-benchmark-example.json\
 tests/abt-io-benchmark-uring-example.json

check_PROGRAMS += \
 tests/basic\
 tests/abt-io-test-init-ext

tests_basic_LDADD = src/libabt-io.la
tests_abt_io_test_init_ext_LDADD = src/libabt-io.la

TESTS += \
 tests/concurrent-write-bench.sh\
 tests/basic\
 tests/abt-io-test-init-ext\
 tests/abt-io-benchmark.sh

if ENABLE_LIBURING
TESTS += \
 tests/basic-uring.sh\
 tests/abt-io-benchmark-uring.sh
endif
